---
features:
  - |
    Enable os-client-config support [1].
    The tempest config tool now is able to support os-client-config env vars
    and cloud.yaml support.

    In order for the tempest config tool to work properly, admin creds should
    be provided, along with the --create option.

    ::

        discover-tempest --create

    [1] https://github.com/openstack/os-client-config
