---
prelude: >
    Add a new ability to remove any configuration values from tempest.conf
features:
  - |
    Add a new parameter --remove to specify which configuration values should
    not be included in tempest configuration file.
    Parameter format:
    [--remove SECTION.KEY=VALUE[,VALUE]]

    If a section or an option specified in CLI does not exist, tempestconf will
    inform a user about that in logging output.
